# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://a7um.github.io
date_format: "ordinal"
title: Atum
subtitle: "Hack and code for FUN!"
description: "Atum's Blog'"
keywords: Atum
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/mzlogin/mzlogin.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Atum
organization: Peking University.
organization_url: https://www.pku.edu.cn
location: Beijing, China
email: lgcpku@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Main

  -
    href: /categories/
    label: Categories

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 12
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: a7um

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitalk
comments_provider: gitalk
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c37570
#disqus_username: Atum

# ---------------- #
#    Analytics     #
# ---------------- #

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: []
skill_mobile_app_keywords: []
skill_windows_keywords: []
